  	<!-- Section: Call To Action -->
  	<section  class="divider parallax layer-overlay overlay-theme-colored2-9" data-bg-img="http://placehold.it/1920x873">
			<div class="container pt-20 pb-20">
				<div class="call-to-action">
					<div class="row">
						<div class="col-md-8 col-md-offset-2 text-center">
              <h2 class="text-theme-colored"><i class="pe-7s-call text-theme-colored"></i><a class="text-theme-colored" href="#"> (+01) &ndash; 234 567 890</a></h2>
							<h2 class="text-white">Please feel free to contact us for emergency case.</h2>
							<p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit rem autem voluptatem obcaecati lienum phaedrum torquatos nec eu, vis detraxit periculis ex.</p>
              <a href="#" class="btn btn-theme-colored mt-20">Contact With Us</a>
						</div>
					</div>
				</div>
			</div>
  	</section>