    <!-- start Doctors Section:-->
    <section id="doctors">
      <div class="container">
        <div class="section-title text-center">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <h2 class=" mt-0 line-height-1">Our <span class="text-theme-colored">Dentist</span></h2>
              <div class="title-icon">
                <img class="mb-10" src="images/title-icon.png" alt="">
              </div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem autem<br> voluptatem obcaecati!</p>
            </div>
          </div>
        </div>
        <div class="row mtli-row-clearfix">
          <div class="col-md-12">
            <div class="owl-carousel-4col">
              <div class="item">
                <div class="team-members border-bottom-theme-color-2px maxwidth400">
                  <div class="team-thumb">
                    <img class="img-fullwidth" alt="" src="http://placehold.it/275x370">
                    <div class="team-overlay"></div>
                  </div>
                  <div class="team-details bg-theme-colored2 p-20">
                    <h4 class="text-uppercase mb-0"><a class="text-white" href="#">Dr. Linda Feldman</a></h4>
                    <p class="text-gray-bbb">Root Canals Dentist</p>
                    <a class="text-gray-ccc font-16" href="#">(+01) - 234 567 890</a>
                    <ul class="styled-icons icon-theme-colored icon-dark icon-circled icon-sm mt-10">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                      <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="team-members border-bottom-theme-color-2px maxwidth400">
                  <div class="team-thumb">
                    <img class="img-fullwidth" alt="" src="http://placehold.it/275x370">
                    <div class="team-overlay"></div>
                  </div>
                  <div class="team-details bg-theme-colored2 p-20">
                    <h4 class="text-uppercase mb-0"><a class="text-white" href="#">Dr. Jessica Tailor</a></h4>
                    <p class="text-gray-bbb">Implant Surgeon</p>
                    <a class="text-gray-ccc font-16" href="#">(+01) - 234 567 890</a>
                    <ul class="styled-icons icon-theme-colored icon-dark icon-circled icon-sm mt-10">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                      <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="team-members border-bottom-theme-color-2px maxwidth400">
                  <div class="team-thumb">
                    <img class="img-fullwidth" alt="" src="http://placehold.it/275x370">
                    <div class="team-overlay"></div>
                  </div>
                  <div class="team-details bg-theme-colored2 p-20">
                    <h4 class="text-uppercase mb-0"><a class="text-white" href="#">Dr. Nichol Fleming</a></h4>
                    <p class="text-gray-bbb">Cosmetic Dental Surgeon</p>
                    <a class="text-gray-ccc font-16" href="#">(+01) - 234 567 890</a>
                    <ul class="styled-icons icon-theme-colored icon-dark icon-circled icon-sm mt-10">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                      <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="team-members border-bottom-theme-color-2px maxwidth400">
                  <div class="team-thumb">
                    <img class="img-fullwidth" alt="" src="http://placehold.it/275x370">
                    <div class="team-overlay"></div>
                  </div>
                  <div class="team-details bg-theme-colored2 p-20">
                    <h4 class="text-uppercase mb-0"><a class="text-white" href="#">Dr. Brian Adam</a></h4>
                    <p class="text-gray-bbb">Restorative Dentist</p>
                    <a class="text-gray-ccc font-16" href="#">(+01) - 234 567 890</a>
                    <ul class="styled-icons icon-theme-colored icon-dark icon-circled icon-sm mt-10">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                      <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>