    <!-- Section: Depertment-->
    <section id="depertment" class="divider parallax layer-overlay overlay-white-9" data-parallax-ratio="0.1" data-bg-img="http://placehold.it/1920x873">
      <div class="container pb-50">
        <div class="section-title text-center">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <h2 class="text-uppercase title">Healthy <span class="text-theme-colored font-weight-300"> Teeth </span>Treatments</h2>
              <p class="text-black">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem autem<br> voluptatem obcaecati!</p>
            </div>
          </div>
        </div>
        <div class="section-content">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 mb-30">
            	<img src="http://placehold.it/370x270" alt="">
              <h3 class=""><a href="#">Dental Implant</a></h3>
              <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit tem autem voluptatem obcaecati.</p>
              <a href="#" class="btn btn-flat btn-theme-colored mt-15 text-theme-color-2">Read More</a>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-4 mb-30">
              <img src="http://placehold.it/370x270" alt="">
              <h3 class=""><a href="#">Dental Bridges</a></h3>
              <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit tem autem voluptatem obcaecati.</p>
              <a href="#" class="btn btn-flat btn-theme-colored mt-15 text-theme-color-2">Read More</a>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-4 mb-30">
              <img src="http://placehold.it/370x270" alt="">
              <h3 class=""><a href="#">Root Canel</a></h3>
              <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit tem autem voluptatem obcaecati.</p>
              <a href="#" class="btn btn-flat btn-theme-colored mt-15 text-theme-color-2">Read More</a>
            </div>
          </div>
        </div>
      </div>
    </section>
