<header id="header" class="header">
    <div class="header-top bg-light sm-text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-6 pb-10 pt-10 pb-sm-0">
            <!-- <div class="widget"> -->
              <i class="fa fa-star-o text-theme-colored"></i> Chandler Dentist 85286: Shumway Dental Care Family, Cosmetic
            <!-- </div> -->
          </div>
          <div class="col-md-6 pb-10 pt-10 pt-sm-0 clearfix sm-text-center">

            <!-- <div class="widget pull-right flip sm-pull-none">
              <div id="side-panel-trigger" class="side-panel-trigger mt-5">
                <a href="#"><i class="fa fa-bars text-theme-colored font-24"></i></a>
              </div>
            </div> -->

            <!-- <div class="widget"> -->
              <!-- <ul class="list-inline pull-right flip sm-pull-none sm-text-center"> -->
                <!-- <li> -->
                <a href="tel:1-480-659-7800" class="pull-right sm-pull-none"><i class="fa fa-phone text-theme-colored"></i> Call Us at 480-659-7800</a>
                <!-- </li> -->
                <!-- <li><i class="fa fa-envelope-o text-theme-colored"></i> <a href="#">contact@yourdomain.com</a></li> -->
              <!-- </ul> -->
            <!-- </div> -->
          </div>
        </div>
      </div>
    </div>
    <div class="header-nav">
      <div class="header-nav-wrapper navbar-scrolltofixed bg-white">
        <div class="container">
          <?php require($config->paths->templates."includes/main-nav.inc"); ?>
        </div>
      </div>
    </div>
  </header>